on: [push]

name: CI

jobs:

  test_remote_install:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main

      - name: Test remote install script
        shell: bash
        run: |
          # Test the remote install script as a user would on a new macOS machine
          # This simulates running: sh -c "$(curl -fsSL https://raw.githubusercontent.com/cearley/dotfiles/remote_install.sh)"
          
          # Create minimal chezmoi data file to prevent prompting
          mkdir -p "$HOME/.config/chezmoi"
          cat > "$HOME/.config/chezmoi/chezmoi.toml" << 'EOF'
          [data]
              fullname = "CI Test"
              gh_email = "ci@example.com"
              gh_username = "cearley"
              keepassxc_db = "~/.local/share/chezmoi/keepassxc.kdbx"
              tags = [
                  "macos",
                  "work"
              ]
          EOF
          
          # Run the script with timeout to prevent hanging (using gtimeout from coreutils)
          brew install coreutils
          gtimeout 300s ./remote_install.sh init || {
            exit_code=$?
            if [ $exit_code -eq 124 ]; then
              echo "❌ Remote install script timed out after 5 minutes"
            else
              echo "❌ Remote install script failed with exit code: $exit_code"
            fi
            exit 1
          }
        env:
          REPO: ${{github.workspace}}

      - name: Verify remote install results
        shell: bash
        run: |
          # Verify that chezmoi was installed and initialized
          if ! command -v chezmoi >/dev/null 2>&1; then
            echo "❌ chezmoi was not installed by remote_install.sh"
            exit 1
          fi
          echo "✅ chezmoi is installed: $(chezmoi --version)"
          
          # Verify that chezmoi source directory exists
          if [ ! -d "$HOME/.local/share/chezmoi" ]; then
            echo "❌ chezmoi source directory was not created"
            exit 1
          fi
          echo "✅ chezmoi source directory exists"

