on: [push]

name: CI

jobs:
  build_and_test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@main
      
      - name: Run bootstrap
        shell: bash
        run: |
          ./hooks/pre/bootstrap
        env:
          REPO: ${{github.workspace}}